// apps/web/components/Calendar.vue
<template>
  <div class="calendar">
    <header>
      <Arrow left @click="toPrev" />
      <div class="month">{{ months[month] }} {{ year }}</div>
      <Arrow @click="toNext" />
    </header>

    <div class="grid">
      <span 
        v-for="(label, idx) in labels" 
        :key="label" 
        class="label"
      >
        {{ labels[(idx + offset) % 7] }}
      </span>

      <template v-for="week in 6">
        <template v-if="current[week - 1]">
          <template v-for="day in 7">
            <template v-if="current[week - 1][day - 1] !== 0">
              <div
                :key="`current-${week}-${day}`"
                class="date"
                :class="{
                  today: isToday(current[week - 1][day - 1]),
                  'has-openings': hasOpenings({ year, month, dayOfMonth: current[week - 1][day - 1] })
                }"
                @click="handleDateClick({ year, month, dayOfMonth: current[week - 1][day - 1] })"
              >
                <span class="text">{{ current[week - 1][day - 1] }}</span>
              </div>
            </template>
            <template v-else-if="week < 2">
              <div :key="`prev-${week}-${day}`" class="date other">
                <span class="text">{{ prev[prev.length - 1][day - 1] }}</span>
              </div>
            </template>
            <template v-else>
              <div :key="`next-${week}-${day}`" class="date other">
                <span class="text">{{ next[0][day - 1] }}</span>
              </div>
            </template>
          </template>
        </template>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import Arrow from './Arrow.vue'
import type { HalfHourOpening } from '@mckaren/types'

const props = defineProps<{
  modelValue: Date
  validDates: Date[]
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: Date): void
}>()

const today = new Date()
const year = ref(today.getFullYear())
const month = ref(today.getMonth())
const offset = 0 // Sun

const labels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

function calendarize(date: Date, offset: number) {
  const year = date.getFullYear()
  const month = date.getMonth()
  
  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  
  const calendar: number[][] = []
  let week: number[] = []
  let day = 1
  
  // Add empty cells for days before the first of the month
  for (let i = 0; i < firstDay.getDay(); i++) {
    week.push(0)
  }
  
  // Add all days of the month
  while (day <= lastDay.getDate()) {
    week.push(day)
    
    if (week.length === 7) {
      calendar.push(week)
      week = []
    }
    
    day++
  }
  
  // Fill out the last week if needed
  while (week.length < 7 && week.length > 0) {
    week.push(0)
  }
  
  if (week.length === 7) {
    calendar.push(week)
  }
  
  return calendar
}

const prev = computed(() => calendarize(new Date(year.value, month.value - 1), offset))
const current = computed(() => calendarize(new Date(year.value, month.value), offset))
const next = computed(() => calendarize(new Date(year.value, month.value + 1), offset))

function toPrev() {
  if (month.value === 0) {
    month.value = 11
    year.value--
  } else {
    month.value--
  }
}

function toNext() {
  if (month.value === 11) {
    month.value = 0
    year.value++
  } else {
    month.value++
  }
}

function isToday(day: number) {
  return year.value === today.getFullYear() && 
         month.value === today.getMonth() && 
         day === today.getDate()
}

function handleDateClick({ year, month, dayOfMonth }: { year: number, month: number, dayOfMonth: number }) {
  emit('update:modelValue', new Date(year, month, dayOfMonth))
}

function isSameDay(date1: Date, date2: Date): boolean {
  return date1.getFullYear() === date2.getFullYear() &&
         date1.getMonth() === date2.getMonth() &&
         date1.getDate() === date2.getDate()
}

function hasOpenings({ year, month, dayOfMonth }: { year: number, month: number, dayOfMonth: number }) {
  const date = new Date(year, month, dayOfMonth)
  return props.validDates.some(validDate => isSameDay(validDate, date))
}
</script>

<style scoped>
.calendar {
  width: 100%;
  max-width: 300px;
}

header {
  display: flex;
  margin-bottom: 1rem;
  align-items: center;
  justify-content: center;
  user-select: none;
}

.month {
  display: block;
  text-align: center;
}

.grid {
  display: grid;
  grid-template-rows: 5% auto;
  grid-template-columns: repeat(7, 1fr);
  text-align: right;
  height: 90%;
  grid-gap: 2px;
}

.label {
  font-weight: 400;
  text-align: center;
  font-size: 0.8rem;
  opacity: 0.6;
}

.date {
  border: 1px solid #bbbbbb;
  position: relative;
  aspect-ratio: 1;
  cursor: pointer;
}

.date:hover {
  background-color: #f3f4f6;
}

.date.today {
  color: #5286fa;
  border-color: currentColor;
}

.date.has-openings {
  background-color: #c4d9fd;
}

.date.other {
  opacity: 0.2;
}

.text {
  position: absolute;
  top: 4px;
  right: 4px;
  font-size: 0.8rem;
}
</style>

// client/src/lib/Calendar.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import _ from 'lodash';
	import calendarize from 'calendarize';
	import Arrow from './Arrow.svelte';

  export let getDateClass = ({}) => '';
	
  const today = new Date();
  let year = today.getFullYear();
	let month = today.getMonth();
	let offset = 0; // Sun

	let labels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
	let months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
	
	let prev = calendarize(new Date(year, month-1), offset);
	let current = calendarize(new Date(year, month), offset);
	let next = calendarize(new Date(year, month+1), offset);
	
	function toPrev() {
		[current, next] = [prev, current];
		
		if (--month < 0) {
			month = 11;
			year--;
		}
		
		prev = calendarize(new Date(year, month-1), offset);
	}
	
	function toNext() {
		[prev, current] = [current, next];
		
		if (++month > 11) {
			month = 0;
			year++;
		}
		
		next = calendarize(new Date(year, month+1), offset);
	}
	
	function isToday(day) {
		return year === today.getFullYear() && month === today.getMonth() && day === today.getDate();
	}

  const dispatch = createEventDispatcher();
  function handleDateClick(date) {
    dispatch('click', date)
  }

  let hoveredDate;

</script>

<header>
	<Arrow left on:click={toPrev} />
	<div class="month"> {months[month]} {year} </div>
	<Arrow on:click={toNext} />
</header>

<div class="grid">
	{#each labels as txt, idx (txt)}
		<span class="label">{ labels[(idx + offset) % 7] }</span>
	{/each}

	{#each { length:6 } as w,idxw (idxw)}
		{#if current[idxw]}
			{#each { length:7 } as d,idxd (idxd)}
				{#if current[idxw][idxd] != 0}
					<div
            on:click={() => handleDateClick({ year, month, dayOfMonth: current[idxw][idxd] })}
            class={`date ${getDateClass({ year, month, dayOfMonth: current[idxw][idxd] })}`}
            class:today={isToday(current[idxw][idxd])}
          >
						<span class="text"> { current[idxw][idxd] } </span>
					</div>
				{:else if (idxw < 1)}
					<div class="date other">
            <span class="text"> { prev[prev.length - 1][idxd] } </span>
          </div>
				{:else}
					<div class="date other">
            <span class="text"> { next[0][idxd] } </span>
          </div>
				{/if}
			{/each}
		{/if}
	{/each}
</div>

<style>
	header {
		display: flex;
		margin-bottom: 1rem;
		align-items: center;
		justify-content: center;
		user-select: none;
	}
	
	.month {
		display: block;
		text-align: center;
	}
	
	.grid {
		display: grid;
    grid-template-rows: 5% auto;
		grid-template-columns: repeat(7, 1fr);
		text-align: right;
    height: 90%;
		grid-gap: 2px;
	}
	
	.label {
		font-weight: 400;
		text-align: center;
    font-size: 0.8rem;
		opacity: 0.6;
	}
	
	.date {
		border: 1px solid #bbbbbb;
    position: relative;
	}
	
	/* .date.today {
		color: #5286fa;
		background: #c4d9fd;
		border-color: currentColor;
	} */
	
	.date.other {
		opacity: 0.2;
	}
  
  .text {
    position: absolute;
    top: 4px;
    right: 4px;
    font-size: 0.8rem;
  }
</style>
